# Generated by Django 6.1 on 2026-08-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0006_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("online", "Online Payment"), ("cod", "Cash on Delivery")],
                default="online",
                max_length=10,
            ),
        ),
    ]
