# Generated by Django 6.1 on 2026-08-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0007_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="fish",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
